---
secrets:
  eso:
    vault:
      server: https://vault-ui.full.cssa.tapsme.org/
      namespace: ""
      auth:
        kubernetes:
          mountPath: tap-gitops
          role: tap-gitops--tanzu-sync-secrets
    remote_refs:
      sync_git:
        # TODO: Fill in your configuration for ssh or basic auth here (see tanzu-sync/app/config/.tanzu-managed/schema--eso.yaml)
        ssh:
          private_key:
            key: secret/dev/tap-gitops/tanzu-sync/sync-git/ssh
            property: privatekey
          known_hosts:
            key: secret/dev/tap-gitops/tanzu-sync/sync-git/ssh
            property: knownhosts
      install_registry_dockerconfig:
        dockerconfigjson:
          key: secret/dev/tap-gitops/tanzu-sync/install-registry-dockerconfig
